#!/bin/bash
17)   mkdir -p welcome/to/school[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[C[C[C[C[C[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cmkdir -p welcome/to/school
